name : 'Terraform Apply'

on:
  push:
    paths:
        - '*.tf'
        - '*.tfvars'
    branches:
        - main
permissions:
    contents: read

jobs:
   terraform:
    runs-on: ubuntu-latest
    name: Terraform Apply
    environment: production
    defaults:
        run:
            shell: bash
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          run: terraform init

        - name: Terraform Plan
          run: terraform plan -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"

        - name: Terraform Apply
          run: terraform apply -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}" --auto-approve --input=false

        - name: Terraform Output
          run: terraform output
        