name : 'Terraform Apply'

on:
  push:
    paths:
        - '*.tf'
        - '*.tfvars'
    branches:
        - main
permissions:
    contents: read

jobs:
   terraform:
    runs-on: ubuntu-latest
    name: Terraform Apply
    environment: production
    defaults:
        run:
            shell: bash
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
        - name : export cloudflare token
          run: |
            export CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
            echo "cloud flare api token starts with ${CLOUDFLARE_API_TOKEN:0:4}..."

        - name: Terraform Init
          run: terraform init
        - name: Terraform Apply
          run: terraform apply --auto-approve --input=false
          
        